# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7677c874c1796a462efb22a41e376a731356b873a07ad7f85f4f5e126a4d64aebc3ed0b9d6ce0c31010345ff429480afb1eaef4206f3495fab03bb802005d9b

test:
  secret_key_base: 166c6275db8b297bac7a153f610f56e59e8d3cfe28154e4187ad70c9ea8a9792982549061acdca798a7190085dfba9bfafbdde5aa658a9523e18195290830f26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
